easy_admin:
    site_name: NivelaU

    design:
        menu:
            - { route: 'default', label: 'Main site', icon: 'home' }
            - { entity: 'Answer', label: 'Preguntas', icon: 'map-marker' }
            - { entity: 'Question', label: 'Respuestas', icon: 'comments' }

    entities:
#        # List the entity class name you want to manage
        - App\Entity\Answer
        - App\Entity\Question
#        - App\Entity\User
