easy_admin:
    site_name: NivelaU

    design:
        menu:
            - { route: 'default', label: 'Main site', icon: 'home' }
            - { entity: 'Question', label: 'Preguntas', icon: 'map-marker' }
            - { entity: 'Answer', label: 'Respuestas', icon: 'comments' }

    entities:
        - App\Entity\Answer
        - App\Entity\Question
